subandpub:
  sub_custom_topic: "/livox/lidar_3JEDM2U001M3641"
  sub_imu_topic: "/livox/imu_3JEDK6L0016N191"
  livox_input_topic: "/livox2"
  foreground_pc_topic: "/dynamic_pointcloud_filtered_2"
  num: "2"

background:
  frame_agg_num: 600
  background_file_name: background_livox_2_e4.pcd
  depth_image_name: "background_depth_2_e4.txt"
  is_background_init: true

  
matrix:
  delta_x: 7.264887
  delta_y: 0.100815
  delta_z: 19.1615

  yaw: 1.04492
  pitch: 0.683049
  roll: -0.0422428